# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.2.20"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.9.0"
kotlinxCoroutines = "1.10.2"
paperweightUserDev = "2.0.0-beta.19"
runPaper = "3.0.2"
paperApi = "1.21.11-R0.1-SNAPSHOT"
configurateKotlinExtras = "4.2.0"
shadow = "9.2.2"
commonsCollections = "4.5.0"
exposed = "1.0.0-rc-3"
h2 = "2.4.240"
postgres = "42.7.8"
foojayResolverConvention = "1.0.0"
libsDisguises = "11.0.9"
flyway = "12.0.0"
icu4j = "78.2"
ktor = "3.4.0"
logback = "1.5.29"
kgraphql = "0.38.0"
jbcrypt = "0.4"
auth0Jwt = "4.4.0"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
paperweightUserDev = { group = "io.papermc.paperweight.userdev", name = "io.papermc.paperweight.userdev.gradle.plugin", version.ref = "paperweightUserDev" }
configurateKotlinExtras = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurateKotlinExtras" }
commonsCollections = { module = "org.apache.commons:commons-collections4", version.ref = "commonsCollections" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-migration-core = { module = "org.jetbrains.exposed:exposed-migration-core", version.ref = "exposed" }
exposed-migration-jbdc = { module = "org.jetbrains.exposed:exposed-migration-jdbc", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
libsDisguises = { module = "me.libraryaddict.disguises:libsdisguises", version.ref = "libsDisguises" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
flyway = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu4j" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-openapi = { module = "io.ktor:ktor-server-openapi", version.ref = "ktor" }
ktor-server-swagger = { module = "io.ktor:ktor-server-swagger", version.ref = "ktor" }
ktor-content-negation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-routing-openapi = { module = "io.ktor:ktor-server-routing-openapi", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kgraphql-ktor = { module = "de.stuebingerb:kgraphql-ktor", version.ref = "kgraphql" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
auth0-jwt = { module = "com.auth0:java-jwt", version.ref = "auth0Jwt" }

# Libraries can be bundled together for easier import
[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
database = ["exposed-core", "exposed-dao", "exposed-jdbc", "exposed-migration-core", "exposed-migration-jbdc", "exposed-kotlin-datetime", "h2", "postgres", "flyway-postgres", "flyway"]
ktor = ["ktor-server-core", "ktor-server-netty", "ktor-server-openapi", "ktor-server-swagger", "ktor-content-negation", "ktor-serialization-kotlinx-json", "ktor-server-routing-openapi", "ktor-server-cors", "ktor-server-call-logging", "ktor-server-auth", "ktor-server-auth-jwt"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
runPaperPlugin = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
paperUserDevPlugin = { id = "io.papermc.paperweight.userdev", version.ref = "paperweightUserDev" }
shadowPlugin = { id = "com.gradleup.shadow", version.ref = "shadow" }
foojayResolverConventionPlugin = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojayResolverConvention" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }